name: skriptarnica
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  flutter_iconly: ^1.0.2
  ionicons: ^0.2.2

  # UI
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  image_picker: 0.8.7+5

  # Memory / State
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1

  # Google Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Opcionalno za geocoding
  geocoding: ^2.0.5                 # <-- ako planiraÅ¡ adresa -> koordinate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets folder - slike i ikone
  assets:
    - assets/images/
    - assets/icons/
